In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3,5,7,4],dtype='i')

In [6]:
b = np.array((2,5,7,9),dtype='f')

In [7]:
print(a)

[1 2 3 5 7 4]


In [8]:
type(a)

numpy.ndarray

In [9]:
type(b)

numpy.ndarray

In [10]:
a.dtype

dtype('int32')

In [11]:
b.dtype

dtype('float32')

# Numpy Dimensions

In [12]:
a = np.array([[1,2,3],[4,5,6]])

# number of dimensions

In [13]:
a.ndim

2

In [14]:
a[0,2]

3

In [15]:
B = np.array([[1,2,3,4],[2,4,5,9]])

In [16]:
B[1,3]

9

In [17]:
C = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[-1,-2,-3],[-4,-5,-6],[-7,-8,-9]]])

In [18]:
C.ndim

3

In [19]:
C[1,0,2]

-3

In [20]:
type(C)

numpy.ndarray

In [21]:
C.shape

(2, 3, 3)

In [22]:
D = np.array([2])

In [23]:
D.ndim

1

In [24]:
E = np.array(3)

In [25]:
E.ndim

0

In [26]:
C.size

18

In [27]:
C.nbytes

72

In [29]:
F = np.arange(100)

In [30]:
print(F)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [31]:
G = np.arange(20,100)
print(G)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69
 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94
 95 96 97 98 99]


In [32]:
H = np.arange(20,100,3) # similar to for i in rqnge(20,100,3)
print(H)

[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77 80 83 86 89 92
 95 98]


In [33]:
print(range(10))

range(0, 10)


In [35]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [37]:
I = np.random.permutation(np.arange(10))
print(I)

[6 1 5 8 3 2 9 4 0 7]


In [39]:
np.random.randint(20,300)

134

In [61]:
K = np.random.rand(1000)

In [62]:
print(K)

[ 0.46543691  0.95890022  0.48943794  0.68690576  0.57776834  0.68747008
  0.85282848  0.27001318  0.91187702  0.80049144  0.68124355  0.59215077
  0.1437951   0.89737329  0.07439103  0.39391486  0.32743732  0.72724926
  0.4847342   0.31817339  0.10474297  0.41206293  0.70112317  0.22518918
  0.14359805  0.52209593  0.68153831  0.65114094  0.15234137  0.77378877
  0.66137552  0.73742123  0.22808342  0.82177334  0.41535826  0.77231507
  0.85060078  0.47821053  0.30167641  0.34742012  0.39060549  0.17933929
  0.81607373  0.61302833  0.88973902  0.94404787  0.42000003  0.87774784
  0.39396709  0.4949093   0.38539868  0.52037119  0.47484319  0.7769517
  0.30842663  0.05965574  0.44717692  0.31598533  0.1110382   0.22449413
  0.07461146  0.39896986  0.57595579  0.83454032  0.33334911  0.4175469
  0.32880525  0.72533439  0.77727325  0.06425936  0.9378388   0.38355482
  0.26732512  0.50250802  0.61680774  0.84682055  0.52454893  0.87051727
  0.99438249  0.86888762  0.10150889  0.84896974  0.0

In [53]:
import matplotlib.pyplot as plt 

In [63]:
plt.hist(K,bins=10)

(array([ 104.,  106.,   90.,  109.,   97.,   95.,  102.,  100.,   99.,   98.]),
 array([ 0.00206983,  0.10169294,  0.20131605,  0.30093916,  0.40056228,
         0.50018539,  0.5998085 ,  0.69943161,  0.79905472,  0.89867783,
         0.99830094]),
 <a list of 10 Patch objects>)

In [64]:
L = np.random.randn(100000)
plt.hist(L,bins=200)

(array([  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          2.00000000e+00,   2.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   3.00000000e+00,   3.00000000e+00,
          2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
          4.00000000e+00,   6.00000000e+00,   3.00000000e+00,
          3.00000000e+00,   7.00000000e+00,   6.00000000e+00,
          8.00000000e+00,   1.00000000e+01,   1.30000000e+01,
          7.00000000e+00,   1.40000000e+01,   1.00000000e+01,
          2.00000000e+01,   1.90000000e+01,   2.30000000e+01,
          2.70000000e+01,   4.00000000e+01,   3.70000000e+01,
          4.20000000e+01,   5.90000000e+01,   5.90000000e+01,
          5.60000000e+01,   6.30000000e+01,   7.40000000e+01,
          8.40000000e+01,   1.03000000e+02,   1.02000000e+02,
          1.09000000e+02,   1.09000000e+02,   1.18000000e+02,
          1.68000000e+02,   1.77000000e+02,   1.83000000e+02,
        

In [65]:
M = np.random.rand(2,3)

In [66]:
M

array([[ 0.77022199,  0.6324102 ,  0.04037408],
       [ 0.26063471,  0.43190264,  0.44884417]])

In [67]:
M.ndim

2

In [68]:
N = np.random.rand(2,3,4,2)

In [69]:
N.ndim

4

In [70]:
O = np.arange(100).reshape(4,25)

In [71]:
O.shape

(4, 25)

In [72]:
print(O)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74]
 [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
  99]]


In [73]:
P= np.arange(100).reshape(4,5,5)

In [74]:
P.shape

(4, 5, 5)

In [75]:
print(P)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]

 [[75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


# Numpy Slicing

In [76]:
Q = np.arange(100)

In [77]:
R = Q[3:10]
print(R)

[3 4 5 6 7 8 9]


In [78]:
R[0] = -1300

In [79]:
print(R)

[-1300     4     5     6     7     8     9]


In [80]:
print(Q)

[    0     1     2 -1300     4     5     6     7     8     9    10    11
    12    13    14    15    16    17    18    19    20    21    22    23
    24    25    26    27    28    29    30    31    32    33    34    35
    36    37    38    39    40    41    42    43    44    45    46    47
    48    49    50    51    52    53    54    55    56    57    58    59
    60    61    62    63    64    65    66    67    68    69    70    71
    72    73    74    75    76    77    78    79    80    81    82    83
    84    85    86    87    88    89    90    91    92    93    94    95
    96    97    98    99]


In [81]:
S = Q[3:10].copy()

In [82]:
Q[::5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [83]:
Q[::-5]

array([99, 94, 89, 84, 79, 74, 69, 64, 59, 54, 49, 44, 39, 34, 29, 24, 19,
       14,  9,  4])

In [88]:
idx = np.argwhere(Q== -1300)[0][0]

In [89]:
print(idx)

3


In [90]:
T = np.round(10*np.random.rand(5,4))

In [91]:
print(T)

[[ 3.  8.  6.  1.]
 [ 9.  4.  6.  9.]
 [ 5.  9.  9.  7.]
 [ 7.  6.  1.  6.]
 [ 2.  6.  9.  8.]]


In [92]:
T[1,2]

6.0

In [93]:
T[1,:]

array([ 9.,  4.,  6.,  9.])

In [94]:
T[:,2]

array([ 6.,  6.,  9.,  1.,  9.])

In [95]:
T[1:3,2:4]

array([[ 6.,  9.],
       [ 9.,  7.]])

In [96]:
T.T  # Transpose

array([[ 3.,  9.,  5.,  7.,  2.],
       [ 8.,  4.,  9.,  6.,  6.],
       [ 6.,  6.,  9.,  1.,  9.],
       [ 1.,  9.,  7.,  6.,  8.]])

In [97]:
import numpy.linalg as la

In [98]:
np.random.rand(3,3)

array([[ 0.01359565,  0.48586065,  0.37945003],
       [ 0.08116075,  0.85858188,  0.13446756],
       [ 0.67343473,  0.70146167,  0.68193945]])

In [99]:
la.inv(np.random.rand(3,3))

array([[-0.42646161,  1.58336723,  0.30526635],
       [-0.07017621, -1.96098311,  1.67872852],
       [ 1.9279511 ,  0.1602172 , -1.56460697]])

In [100]:
print(T)

[[ 3.  8.  6.  1.]
 [ 9.  4.  6.  9.]
 [ 5.  9.  9.  7.]
 [ 7.  6.  1.  6.]
 [ 2.  6.  9.  8.]]


In [101]:
T.sort(axis=0)

In [102]:
print(T)

[[ 2.  4.  1.  1.]
 [ 3.  6.  6.  6.]
 [ 5.  6.  6.  7.]
 [ 7.  8.  9.  8.]
 [ 9.  9.  9.  9.]]


In [103]:
T.sort(axis=1)

In [104]:
print(T)

[[ 1.  1.  2.  4.]
 [ 3.  6.  6.  6.]
 [ 5.  6.  6.  7.]
 [ 7.  8.  8.  9.]
 [ 9.  9.  9.  9.]]


In [105]:
U = np.arange(100)

In [106]:
V = U[[3,5,6]]

In [107]:
print(V)

[3 5 6]


In [108]:
print(U)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [109]:
W = U[U<40]

In [110]:
print(W)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [111]:
X = U[(U<40) & (U >30)]

In [112]:
print(X)

[31 32 33 34 35 36 37 38 39]


# & used for Arrays : and used for objects
# | used for Arrays : or used for objects
# ~ used for Arrays : not used for objects

In [114]:
Y = np.round(10*np.random.rand(2,3))

In [115]:
print(Y)

[[ 7.  9.  8.]
 [ 9.  6.  5.]]


In [116]:
print(Y+3)

[[ 10.  12.  11.]
 [ 12.   9.   8.]]


In [117]:
print(Y)

[[ 7.  9.  8.]
 [ 9.  6.  5.]]


In [118]:
Y + (np.arange(2).reshape(2,1))

array([[  7.,   9.,   8.],
       [ 10.,   7.,   6.]])

In [119]:
Z = np.round(10*np.random.rand(2,2))

In [120]:
AZ = np.hstack((Y,Z))

In [121]:
print(AZ)

[[ 7.  9.  8.  4.  2.]
 [ 9.  6.  5.  9.  8.]]


In [122]:
AA = np.random.permutation(np.arange(10))

In [123]:
print(AA)

[5 2 7 9 1 0 3 6 8 4]


In [124]:
AA.sort()

In [125]:
print(AA)

[0 1 2 3 4 5 6 7 8 9]


In [126]:
AA = AA[::-1] # sorting descending order

In [127]:
print(AA)

[9 8 7 6 5 4 3 2 1 0]


In [128]:
AB = np.array(["abc","how are you? ",'u765','13er'])

In [129]:
print(AB)

['abc' 'how are you? ' 'u765' '13er']


In [130]:
AB.sort()

In [131]:
print(AB)

['13er' 'abc' 'how are you? ' 'u765']


In [132]:
AC = np.random.rand(1000000)
%timeit sum(AC)
%timeit np.sum(AC) # AC.sum

1 loop, best of 3: 394 ms per loop
1000 loops, best of 3: 1.48 ms per loop


In [133]:
def mySum(G):
    s = 0
    for x in G:
        s+=x
    return s


In [134]:
%timeit mySum(AC)

1 loop, best of 3: 492 ms per loop
